version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: saul
      POSTGRES_PASSWORD: tu_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build: 
      context: backend/core
      dockerfile: Dockerfile
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend/core:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://saul:tu_password@db:5432/mydb
      ALLOWED_HOSTS: localhost,127.0.0.1,backend,frontend
      CORS_ALLOWED_ORIGINS: http://localhost:3000,http://frontend:5173
      CSRF_TRUSTED_ORIGINS: http://localhost:3000,http://frontend:5173
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      VITE_BACKEND_URL: http://backend:8000
    command: sh -c "npm install && npm run dev"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge